# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 08:35
from __future__ import unicode_literals

import articles.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique_for_year=b'publish_date')),
                ('keywords', models.TextField(blank=True, help_text='If omitted, the keywords will be the same as the article tags.')),
                ('description', models.TextField(blank=True, help_text="If omitted, the description will be determined by the first bit of the article's content.")),
                ('markup', models.CharField(choices=[(b'h', 'HTML/Plain Text'), (b'm', 'Markdown'), (b'r', 'ReStructured Text'), (b't', 'Textile')], default=b'h', help_text='Select the type of markup you are using in this article.\n<ul>\n<li><a href="http://daringfireball.net/projects/markdown/basics" target="_blank">Markdown Guide</a></li>\n<li><a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_blank">ReStructured Text Guide</a></li>\n<li><a href="http://thresholdstate.com/articles/4312/the-textile-reference-manual" target="_blank">Textile Guide</a></li>\n</ul>', max_length=1)),
                ('content', models.TextField()),
                ('rendered_content', models.TextField()),
                ('auto_tag', models.BooleanField(default=True, help_text='Check this if you want to automatically assign any existing tags to this article based on its content.')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, help_text='The date and time this article shall appear online.')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Leave blank if the article does not expire.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('login_required', models.BooleanField(help_text='Enable this if users must login before they can read this article.')),
                ('use_addthis_button', models.BooleanField(default=True, help_text='Check this to show an AddThis bookmark button when viewing an article.', verbose_name='Show AddThis button')),
                ('addthis_use_author', models.BooleanField(default=True, help_text="Check this if you want to use the article author's username for the AddThis button.  Respected only if the username field is left empty.", verbose_name="Use article author's username")),
                ('addthis_username', models.CharField(blank=True, default=None, help_text='The AddThis username to use for the button.', max_length=50, verbose_name='AddThis Username')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followup_for', models.ManyToManyField(blank=True, help_text='Select any other articles that this article follows up on.', related_name='followups', to='articles.Article')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='_article_related_articles_+', to='articles.Article')),
                ('sites', models.ManyToManyField(blank=True, to='sites.Site')),
            ],
            options={
                'ordering': ('-publish_date', 'title'),
                'get_latest_by': 'publish_date',
            },
        ),
        migrations.CreateModel(
            name='ArticleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ordering', models.IntegerField(default=0)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('ordering', 'name'),
                'verbose_name_plural': 'Article statuses',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=articles.models._get_attachment_upload_name)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='articles.Article')),
            ],
            options={
                'ordering': ('-article', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('link_name', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-id', 'create_time'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(default=articles.models._get_default_article_status, on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleStatus'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags that describe this article', to='articles.Tag'),
        ),
    ]
